### PR TITLE
Change vocab equal hugginface

### PR DESCRIPTION
**Pull request by ZanezZephyrs**
Maybe it is safer to use 50400 as the vocab size since it is the number used in the gpt-j [available in hugginface](https://huggingface.co/EleutherAI/gpt-j-6B/blob/main/config.json)?

### CODE REVIEW

**Review by rodrigonogueira4 — APPROVED** [review]

**Comment by piresramon** [comment]
I don't know if this could cause any problems. For TPU performance, they recommend using multiple of 128. 
I was checking [gpt-neo](https://github.com/EleutherAI/gpt-neo/blob/master/configs/gpt3_large_256.json#L3) and [gpt-neox](https://github.com/EleutherAI/gpt-neox/blob/e70f3901fb27bf7194f397af5ddc0e5a42db5cdc/tools/merge20b.py#L9). GPT-Neo seems to use 50304 while GPT-NeoX uses 50432.

**Comment by rodrigonogueira4** [comment]
Ah, sorry @ZanezZephyrs... @piresramon is right: we cannot use 50400 as it is not a multiple of 128 (TPUs need this rounding for efficiency reasons). The best is 50304.

**Comment by piresramon** [comment]
Just thinking a little bit about it: could using a vocab size different from GPT-J  be a problem when loading the checkpoint? If the embedding size does not match, the layer will start from scratch, right?

**Comment by rodrigonogueira4** [comment]
Since the vocabulary is different anyway, I don't think that starting from scratch would be a problem

**Comment by rodrigonogueira4** [comment]
Thinking about it again... I think we should keep it at 50400. We actually don't need it to be a multiple of 128... a multiple of 16 would do..

**Comment by hugoabonizio** [comment]
@rodrigonogueira4 is the model parallelism only linked to the number of heads? (16 to GPT-J and 64 to GPT-NeoX)

**Comment by rodrigonogueira4** [comment]
I think it is linked to any vector... otherwise the FFN layers wouldn't have model parallelism

**Comment by ZanezZephyrs** [comment]
We discussed this matter in the daily meeting, it was decided that we will be using the same vocabulary size as the original gpt-j, therefore i will be merging this PR.

**Review by piresramon — APPROVED** [review]

**Pull request merged**
